name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Tidy
      run: go mod tidy

    - name: Test
      run: go test -v ./tests

    - name: Build
      run: go build -v ./cmd/lazypm
